language: ruby
cache:
  -bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
addons:
  code_climate:
    repo_token:
      secure: "IBQdXqdWdfTPduZhn4GJ/K0gcPY+1pJRH8AQvnoRTHWFrtOUAiLjPDycoyGA46BG4Zp5OOLeOloPvgctN80I7utVlg43bqZUgykCuBQRhW2yVN1eoBMDhhQ1zhDAuTCmI4Cpnj2ly1xQF4sKNxTOZNZmk+MTtEurFbewju+a518="
